AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - bin/**/*
    - db/**/*
    - spec/**/*_spec.rb
Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false